name: s-php
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - .data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    profiles:
      - mysql

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    profiles:
      - postgres

  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh entrypoint.sh
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    environment:
      DB_CONNECTION: ${DB_CONNECTION:-sqlite}
      DB_DATABASE: ${DB_DATABASE:-/var/www/html/.data/database.sqlite}
      DB_HOST: ${DB_HOST:-}
      DB_PORT: ${DB_PORT:-}
      DB_USERNAME: ${DB_USERNAME:-}
      DB_PASSWORD: ${DB_PASSWORD:-}
